In [2]:
import torch

In [3]:
# that sets the random number generator seed for torch. This function is used to control the random number generation
torch.manual_seed(7)

In [4]:
#it generates random no's
features=torch.randn((1,5))
features

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])

In [5]:
#it generates random no's like the parameter provided
weights=torch.randn_like(features)
weights

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [6]:
bias=torch.randn((1,1))
bias

tensor([[0.3177]])

In [7]:
# sigmoid activation function
def activation_function(x):
    return 1/(1+torch.exp(-x))

In [8]:
y=activation_function(torch.sum(features*weights)+bias)
y

tensor([[0.1595]])

In [9]:
#it support broadcasting if input shape have weird size and shape you will get output you dont expect
torch.matmul()

TypeError: matmul() missing 2 required positional argument: "input", "other"

In [ ]:
#it gives error if array has weird size and shape not doing the calculations
torch.mm()

In [10]:
#new tensor with same data sometimes clones, copies data into another part of memory
weights.reshape()

# _(inplace) you are not touching the at all. return the same tensor with different shape
weights.resize_()

#new tensor with same data as weights with size a,b
weights.view()

TypeError: reshape() missing 1 required positional arguments: "shape"